// Generated by https://quicktype.io


    public partial class Notification
    {
        public string[] SubscriptionIds { get; set; }

        public string Tag { get; set; }

        public NotificationPayload NotificationPayload { get; set; }

        public object Meta { get; set; }
    }

    public partial class NotificationPayload
    {
        public string Title { get; set; }

        public Action[] Actions { get; set; }

        public string Body { get; set; }

        public string Dir { get; set; }

        public Uri Icon { get; set; }

        public Uri Badge { get; set; }

        public string Lang { get; set; }

        public bool Renotify { get; set; }

        public bool RequireInteraction { get; set; }

        public string Tag { get; set; }

        public long[] Vibrate { get; set; }
    }

    public partial class Action
    {
        public string CustomAction { get; set; }

        public string Title { get; set; }
    }

    